apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuvvai-backend-deployment
  labels:
    app: nuvvai-backend-deployment
    kind: backend
  namespace: nuvvai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuvvai-backend-pod
      kind: backend
  template:
    metadata:
      name: nuvvai-backend-pod
      labels:
        app: nuvvai-backend-pod
        kind: backend
    spec:
      containers:
        - image: hazem196/nuvvai-backend
          name: nuvvai-backend
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: mongodb://nuvvai-database-service
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nuvvai-backend-service
  labels:
    app: nuvvai-backend-service
    kind: backend
  namespace: nuvvai
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: nuvvai-backend-pod
    kind: backend
